# -*- coding: utf-8 -*-
"""Santiago Acevedo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQRvW8xhGxbEDGwkJMKSKPCFZd09NiAE
"""







"""# Corte 1

Leccion 1 -Fundamentos de phyton

"""

print("Hola mundo")

nombre=input("¿Cual es tu nombre?")

print("Hola mundo de",nombre)

nombre="santiago"
edad=20
altura=1.84
correo="ironmancampeon@gmail.com"
soltero=False

print("Tipo de dato:")
print(type(nombre))
print(type(soltero))
print(type(altura))
print(type(correo))
print(type(edad))

print("Hola", nombre, "tienes", edad-10 )

"""CLASE 2( 24 DE AGOSTO)"""

#oPERACIONES MATEMATICAS

vab1=20
vab2=15

print(vab1 + vab2)

print("La suma es:", vab1 + vab2)

vab1 = 20
vab2 = 15

suma=vab1 + vab2

print(vab1,"+",vab2, "=", suma)

vab1 = 20
vab2 = 15

suma=vab1 + vab2
resta=vab1 - vab2
multi=vab1 * vab2
divi=vab1 / vab2

print(vab1,"+",vab2, "=", suma)
print(vab1,"-",vab2, "=", resta)
print(vab1,"*",vab2, "*", multi)
print(vab1,"/",vab2, "/", divi)

nombre = input("Indicanos tu nombre: ")

print("Por favor indicame 3 notas para calcular el promedio")

nota1 = float(input("Nota 1: "))
nota2 = float(input("Nota 2: "))
nota3 = float(input("Nota 3: "))
suma=(nota1+nota2+nota3)
promedio=suma/3
print("suma de notas", suma)
print("El promedio de notas es", promedio)

print("Bienvenidos a la Tienda Santiago")
Nombredelproducto="Queso"
Cantidad=int(input("¿Cuantos queso compraste?"))
PrecioQueso=5000
Subtotal=PrecioQueso * Cantidad
print("El subtotal es",Subtotal)

#Parte 2 - Santiago Acevedo
IVA = 19/100
costoIVA= Subtotal * IVA
print("El valor del IVA 19% es", costoIVA)


#Parte 3

Totalpagar = Subtotal + costoIVA
print("Total a pagar: $", Totalpagar)

"""CAFETERIA UNIVERSITARIA"""

print("BIENVENIDO A LA TIENDA UNIVERSITARIA")
cantidad_productos = int(input("ingresa la cantidad de productos comprados?"))
precio_unitario = float(input("precio unitario de cada producto"))
subtotal = cantidad_productos * precio_unitario
print("El subtotal es",subtotal)
descuento = subtotal * 0.10
print("El descuento es", descuento)
total_a_pagar_sin_IVA = subtotal - descuento
print("El total a pagar sin IVA es:", total_a_pagar_sin_IVA)
vab1IVA = 19 / 100
costoIVA = vab1IVA * total_a_pagar_sin_IVA
print("Costo del IVA 19%:", costoIVA)
total_final= total_a_pagar_sin_IVA + costoIVA
print("el total final es:",total_final)

"""VIAJE EN AUTOMOVIL"""

distancia =float(input ("distancia del viaje en km"))
print ("¿cual es la distancia del viaje en km?", distancia)
rendimiento_automovil = float(input( "el rendimiento del automovil"))
print("¿cual es el rendimiento del automovil en km x L?" ,rendimiento_automovil)
precio_litro_gasolina = float(input ("precio litro gasolina"))
print("¿cual es el precio L de la gasolina?", precio_litro_gasolina)
litro_necesarios_de_gasolina = distacia / rendimiento_automovil
print("litros _necesarios de gasolina", litro_necesarios_de_gasolina )
costototal= litro_necesarios _de gasolina * precio_litro_gasolina
print("El costo total del combustible es de: ", costototal)

precio_aumento_gasolina=(precio_litro_gasolina * 8/100)
precio_litro_gasolina-precio_litro_gasolina + precio_aumento_gasolina

costo_para3 = (litro_necesarios_de gasolina * precio_litro_gasolina) /3
print("El valor a pagar para cada uno es: $", costo_para3)

print("costo de ida y vuelta es $", precio_li)

"""Clase 07/09  Ciclos For y While"""

num1 = int(input("Dame un numero: "))
num2 = int(input("Dame un numero: "))
num3 = int(input("Dame un numero: "))

suma=num1+num2+num3
print("La suma es: ", suma)

cuantosnumerosumar = int(input("¿Cuantos numeros deseas sumar?"))

acumuladosuma=0

for i in range(cuantosnumerosumar):
  numero = int(input("Dame el numero que quieres sumar"))
  acumuladosuma = acumuladosuma + numero

  print("La suma es ", acumuladosuma)

for i in range(5):
 print("i=", i)

for i in range(3):
  print("Esta por dentro del bucle ", i,"vez")
print("Esta por fuera")

#Caso 1

print("#Caso 1")
for i in range(5):
 print("i=", i)

#Caso 2
print("#Caso 2")
for i in range(1,8):
  print("i=", i)

#Caso 3
print("#Caso 3")
for i in range(1,20,2):
  print("i=", i)

notas = [3.5, 4.2, 2.8, 5.0]
for notas in notas:
  print("La nota es:", notas)

notas = [3.5, 4.2, 2.8, 5.0]
suma = 0
for nota in notas:
    suma = suma + nota
print("Promedio:", suma / len(notas))

n = 5
while n > 0:
   print(n)
   n = n - 1
print("¡Despegue!")

edad = int(input("Tu edad: "))

while edad < 1 or edad >50:
  print("Eso no es valido")
  edad= int(input("Tu edad es: "))

for i in range(10):
 print("i=+", i)

"""For y While Ejercicios


"""

for numero in range(1,21):
  print("numero=", numero)

for tabla7 in range(1,11):
  print("7*",tabla7, "=", 7*tabla7)

total = 0
for i in range(3):
  precio = float(input("Precio: "))
  total = total + precio
  print("total=", total)

precios = [1200,3500,800]
total = 0
for p in precios:
  total = total + p
  print("total=", total)

numero = int(input("Ingresa un numero positivo"))
while numero < 0:
  print("Numero invalido")
  numero = int(input("No es positivo. Intenta de nuevo"))

contador = 10

while contador > 0:
  print(contador)
  contador = contador - 1
print("¡Feliz año!")

for i in range(2, 31, 2):
  print(i)

edad = int(input("Ingrese su edad: "))

if edad < 0:
    print("Edad no valida")
elif edad < 12:
    print("Niño")
elif edad < 18:
    print("Adolescente")
elif edad < 60:
    print("Adulto")
elif edad >= 60:
    print("Adulto Mayor")

nota = float(input("Ingrese su nota final (0.0 a 5.0): "))

if nota < 0.0 or nota > 5.0:
    print("Valor fuera de rango")
elif nota >= 3.0:
    print("Aprobó")
elif nota >= 2.5:
    print("Habilitacion")
else:
  print("Reprobo")

rol = input("Ingrese su rol (estudiante/docente/administrador): ")

if rol == "estudiante":
    print("Bienvenido/a estudiante")
elif rol == "docente":
    print("Bienvenido/a docente")
elif rol == "administrador":
    print/"Bienvenido/a administrador"
else:
    print("Rol no reconocido")

peso = float(input("Ingrese su peso en kg: "))
estatura = float(input("Ingrese su estatura en metros: "))
imc = peso / (estatura ** 2)

if imc < 18.5:
    print("Bajo peso")
elif imc < 24.9:
    print("Peso normal")
elif imc < 29.9:
    print("Sobrepeso")
elif imc < 30.0:
    print("Obesidad")
else:
    print("Obesidad")

compra = float(input("Ingrese el valor de la compra: "))
respuesta = input("¿Es estudiante? (si/no): ")
es_estudiante = respuesta.lower().strip() == "si"

descuento = 0.0
if es_estudiante:
    descuento = descuento + 0.15
if compra > 200000:
     descuento = descuento + 0.05

total = compra * (1 - descuento)
print("Total a pagar:", total)

"""ESTRUCTURAS DE DATOS - 28709/2026"""

listanumeros =  [2, 3.5, 4, 100]

print(type(listanumeros))
print("tamaño lista =",len(listanumeros))

print(listanumeros)
print("Los valores en la lista son:")
i=0
for valor in listanumeros:
  print("listanumeros[",i, "] =", valor)
  i+=1

listafrutas = ["manzana", "pera", "fresa"]
print(listafrutas)

listafrutas[1] = "mango"
print(listafrutas)

datosperso = ["Santiago", 29, 1.83, "dacevedo245@unab.edu.co", "altos de cañaveral", "cañaveral"]
print(datosperso)

print("Formulario")
nombre = input("idicame tu nombre")
edad = int(input("La edad:"))
altura = float(input("dame tu altura:"))
correo = input("Indicame tu correo: ")
direccion = input("Indicame tu direccion:")
barrio = input("Indicame tu barrio:")

listausuario = [nombre, edad, altura, correo, direccion, barrio]
print(grupoClase)

grupoClase = [lisatUsuario, listaUsuario, listaUsuario, listaUsuario]
print(grupoClase)

"""Clase 05/10  Listas

Enunciado
Doña Marta tiene una tienda de barrio y recibe pedidos por WhatsApp. Para no perder el hilo, guarda cada pedido en una sola lista con estos datos, en este orden: el nombre del cliente (texto), el número de productos (entero), el total a pagar (decimal), si ya pagó (verdadero o falso) y la dirección de entrega (texto). El pedido de hoy es el de Laura:
pedido = ["Laura Gómez", 3, 45500.0, False, "Calle 45 #12-30"]
Durante la mañana el pedido va cambiando y doña Marta necesita que tu programa lo vaya actualizando sobre la misma lista, sin volver a crearla desde cero. Sigue las instrucciones en orden y usa un print para mostrar el resultado de cada paso.
Qué debe hacer tu programa
1. Crea la lista e imprime el nombre del cliente (índice positivo) y la dirección de entrega (índice negativo, sin contar cuántos elementos hay).
2. Laura agregó dos productos más y el total subió a $62.300. Además, ya pagó por transferencia. Corrige esos tres datos directamente en sus posiciones.
3. Doña Marta quiere guardar el teléfono de Laura, "3001234567" (como texto), justo después del nombre, y el nombre del domiciliario, "Andrés", al final de la lista.
4. Agrega al final la hora estimada de entrega: 10 (hora) y 30 (minutos), cada uno como un elemento independiente de la lista. Imprime la lista completa y cuántos elementos tiene.
5. Usando :, imprime en un print distinto cada uno de estos cortes: (a) nombre y teléfono; (b) número de productos, total y estado de pago; (c) los tres últimos datos; (d) toda la lista en orden inverso.
Entrega: escribe el programa en Python, ejecútalo y anexa una captura de pantalla del código y otra del resultado impreso en consola.
Preguntas trampa
A. Un compañero resolvió el paso 4 con otra instrucción y su lista quedó con 8 elementos en vez de 9. ¿Qué hizo diferente y qué obtiene al imprimir el último elemento de su lista?

B. Otro compañero, ya hecho el paso 3, escribe pedido[4] esperando obtener la dirección de entrega. ¿Qué valor y de qué tipo recibe realmente, y por qué dejó de ser la dirección?
"""

pedidos = ["Laura Gomez", 3, 45500.0, False, "Calle 45 #12-30"]
print("Nombre = ", pedidos[0])
print("Direccion = ", pedidos[-1])


pedidos = ["Laura Gomez", 5, 62300.0, True, "Calle 45 #12-30"]
print(pedidos)



pedidos = ["Laura Gomez", "3001234567", 5, 62300.0, True, "Calle 45 #12-30", "Andres", "10:30"]
print(pedidos)






pedidos.append(("10, 30"))
print(pedidos)
print(len(pedidos))


print("Primer mensaje")
print(pedidos[0:2])
print("Segundo mensaje")
print(pedidos[2:5])
print("Tercer mensaje")
print(pedidos[4:7])
print("Cuarto mensaje")
print(pedidos[-1:-10])

listanumeros = [5, 50, 100, 200]

print(listanumeros)

for num in listanumeros:
  print(num)

print("lista numeros: ", len(listanumeros))


for i in range(1,4,2):
  print("listanumeros(",1,")=", listanumeros[1])

thislist = ["apple", "banana", "cherry"]
1 = 0
print(i)
while i = len(thislist):
  print(1, "<", len(thislist))
  print("thislist(")